#----------------------------------------------------------------------
# standard track-level option sets, invoked in track type settings.yml as:
#   include:
#       - height 
#       - xyOptions
#       - etc.
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# options always added to all tracks (you don't need to include this option set)
#----------------------------------------------------------------------
allTracks: 
    Track_Options:
        Track_Name: 
            type:   textInput
            value:  auto # populated by browserTrackServer
        Top_Padding:
            type:   numericInput
            value:  0.02
            min:    0
            max:    1
            step:   0.02            
        Y_Axis_Label: 
            type:   textInput
            value:  auto # ylab is set by track.R when Y_Axis_Label = auto           
        Bottom_Padding:
            type:   numericInput
            value:  0.02
            min:    0
            max:    1
            step:   0.02

#----------------------------------------------------------------------
# option sets you may include as needed, i.e., that only apply to certain track types
#----------------------------------------------------------------------
height: 
    Track_Options:
        Height: 
            type:   numericInput
            value:  2
            min:    1
            max:    5
            step:   0.5
box: 
    Track_Options:
        Bounding_Box: 
            type:   checkboxInput
            value:  false 
scaleUnit:  
    Plot_Options: 
        Scale_Unit:
            type: selectInput
            choices:
                - auto
                - Mb
                - kb
                - bp
            value: auto
yAxisLimit:
    Track_Options:
        Y_Limit:
            type: textInput
            value: auto # ylim is set by track.R when Y_Limits = auto 
hLines:
    Track_Options:
        Horizontal_Lines:
            type: checkboxInput
            value: true          
xyOptions:
    Plot_Options:
        Plot_As:
            type: selectInput
            choices:
                - points
                - lines 
                - both 
                - area 
                - histogram
            value: points
        Point_Symbol:
            type: selectInput
            choices:
                - open_circles
                - filled_circles 
                - open_squares 
                - filled_squares
            value: filled_circles             
        Line_Width:
            type: numericInput
            value:  1
            min:    0.25
            max:    5
            step:   0.25                 
        Point_Size:
            type: numericInput
            value:  1
            min:    0.25
            max:    5
            step:   0.25  
lineWidth: 
    Plot_Options:
        Line_Width:
            type: numericInput
            value:  1
            min:    0.25
            max:    5
            step:   0.25                
colorPlotly:
    Plot_Options:
        Color:
            type: selectInput
            choices:
                - auto
                - blue
                - orange
                - green
                - red
                - purple
                - brown
                - pink
                - gray
                - yellow
                - teal
                - black
                - grey 
            value: auto
# backgroundShading:
#     Plot_Options:
#         Background_Shading:
#             type: selectInput
#             choices:
#                 - pending
