# template for settings relevant to the __MODULE_NAME__ browserTrack type

# uncomment this section to include standard settings from widgets/browserTrack/settings.yml
# see: https://github.com/wilsontelab/genomex-mdi-tools
# include:
#     - height

# uncomment this section to specify custom settings, using the same format as for settingsServer
# see: https://midataint.github.io/mdi-apps-framework/docs/settings/yaml-declarations.html
settings:
    Track:
        Y_Axis_Label:
            type:   textInput
            value:  none
        Height:
            type:   numericInput
            value:  0.8
            min:    0.4
            max:    1.6
            step:   0.1   
    Plot_Options:  
        Line_Weight: 
            type:   numericInput
            value:  2
            min:    0.25
            max:    5
            step:   0.25
        Palette:
            type: selectInput
            choices:
                - green/red
                - blue/orange
            selected: green/red   
        Max_Genes_BP: 
            type:   numericInput
            value:  50000000
            min:    0
            max:    250000000
            step:   10000000     
        Max_Exons_BP: 
            type:   numericInput
            value:  1000000
            min:    0
            max:    100000000
            step:   100000
        Min_Gene_Size_Label: 
            type:   numericInput
            value:  1000
            min:    0
            max:    10000
            step:   500 
        Force_Gene_Labels: 
            type:   textInput
            value:  ""
