include:
    - scaleUnit
settings:
    Track_Options:
        Height: 
            type:   numericInput
            value:  0.2
            min:    0.05
            max:    1
            step:   0.05    
    Plot_Options:
        Feature_Track:
            type:   selectInput
            choices:
                - cytoBand
                - gap
                - none
            value: cytoBand
