#----------------------------------------------------------------------
# R package dependencies common to many apps
#----------------------------------------------------------------------
# packages:
#   R:  
#     - xxx
#     - yyy
#   Bioconductor: null
